# Laboratorio 2
# Parte 1
El primer ejercicio de práctica deberás realizar el código usando las funciones y bibliotecas Panda en Python, con el respectivo grafico según el caso, escribir el respectivo código y mostrar el resultado, aplicar los temas vistos en clase.
1. Ejercicio de práctica 1.
- Crear un DataFrame con los nombres, profesión y países de 8 personas, y luego imprimir el DataFrame

In [3]:
import pandas as pd
data = {
    'Nombre':['Fabian', 'Ana', 'Patricia', 'Linda'],
    'Edad': [28, 24, 35, 32],
    'Ciudad': ['Bogota', 'Pereira', 'Bucaramanga', 'Cali']
}
df = pd.DataFrame(data)
print(df)

     Nombre  Edad       Ciudad
0    Fabian    28       Bogota
1       Ana    24      Pereira
2  Patricia    35  Bucaramanga
3     Linda    32         Cali


- Cargar un archivo CSV (puedes usar un archivo de ejemplo en tu entorno) y mostrar las 
primeras 5 filas.

In [4]:
import pandas as pd
df = pd.read_csv("data.csv")
df

Duracion  Pulso  Maxpulso  Calorias
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

- Generar un DataFrame con 100 filas y 8 columnas de valores aleatorios, y luego mostrar un resumen estadístico de los datos.

In [6]:
import pandas as pd
df = pd.read_json("data.json")
df

Duracion  Pulso  Maxpulso  Calorias
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

# Parte 2
El segundo ejercicio de práctica deberás realizar el código usando las funciones y bibliotecas Numpy en Python, con el respectivo grafico según los escenarios, escribir el respectivo código y mostrar el resultado, aplicar los temas vistos en clase.

2. Ejercicio de práctica 2.

- Crear un array de números del 1 al 10 y mostrar la suma, la media, y el valor máximo.

In [11]:
import numpy as np
array = np.arange(1,11)
print(array)
print("Suma: ",array.sum())
print("Media: ",array.mean())
print("Máximo: ",array.max())

[ 1  2  3  4  5  6  7  8  9 10]
Suma:  55
Media:  5.5
Máximo:  10


- Crear un array de 3x4 lleno de ceros y luego cambiar su forma a 2x6

In [12]:
import numpy as np
array = np.zeros((3,4))
print("Array original de (3x4)")
print(array)
print()
array=array.reshape(2,6)
print("Array despues de reshape (2x6)")
print(array)

Array original de (3x4)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array despues de reshape (2x6)
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


- Generar una matriz aleatoria de 3x3 y calcular su transpuesta.

In [13]:
import numpy as np
array=np.random.rand(3,3)
print("Matriz Original")
print(array)
print()
traspuesta=array.T
print("Matriz transpuesta")
print(traspuesta)

Matriz Original
[[0.71526369 0.44060191 0.81501657]
 [0.82208701 0.80330074 0.02435778]
 [0.22042624 0.46145889 0.55068146]]

Matriz transpuesta
[[0.71526369 0.82208701 0.22042624]
 [0.44060191 0.80330074 0.46145889]
 [0.81501657 0.02435778 0.55068146]]


- Concatenar dos arrays de NumPy, cada uno con 5 valores, y luego imprimir el array concatenado

In [14]:
import pandas as pd
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
arr_concatenado=np.concatenate((a,b))
print("Array concatenado ", arr_concatenado)

Array concatenado  [ 1  2  3  4  5  6  7  8  9 10]
